### ISSUE TITLE
Not working Locally

### ISSUE THREAD

**Issue by ayush20501** [Thiru-Malai/ChatGPT-WhatsappBot-Twilio#3]
i am running the free-trail main.py locally but it's showing not found error!

**Comment by Thiru-Malai** [comment]
Can you send screenshots of the error?
It will be helpful for fixing.

Also let me know what have you done so that I can reproduce the error

**Comment by Thiru-Malai** [comment]
To run your app in local you need to follow these steps:

```
mkdir chatgpt
cd chatgpt
python3 -m venv

For Linux un: source venv/bin/activate
For Windows run: venv/Scripts/activate

pip install twilio flask requests
```
Create a main.py in root directory

The hierarchy should be like this:

![image](https://user-images.githubusercontent.com/73980589/233764918-3d0e13ba-4ba9-42c3-952e-63576119541d.png)

Copy the code from Free-Trial (Code Updated) into main.py

**NGROK Local Deployment:**

Now download ngrok

1. https://ngrok.com/download
2. Extract the zip and add the folder to the environment variables
3. Login to ngrok website: https://dashboard.ngrok.com/get-started/setup
4. run ngrok config add-authtoken <your-auth-token> in terminal

![Ngork](https://user-images.githubusercontent.com/73980589/233765094-ef70a5bb-758f-48e4-85a8-175a3f8d9213.png)

5. run ngrok http 5000
The output should be like 

![image](https://user-images.githubusercontent.com/73980589/233765125-16c431a9-3f7f-4ea0-9456-4386153cdee0.png)

6. Copy the Forwarding URL from the terminal and paste it in Twilio console and WhatsApp sandbox settings:
Paste the URL appended with /bot
Original Url: https://2262-49-204-133-70.ngrok-free.app/ 
Appended Url:https://2262-49-204-133-70.ngrok-free.app/bot

![image](https://user-images.githubusercontent.com/73980589/233765139-fa1ab46a-b334-4b35-919b-c5acc922bb4e.png)


Now run the main.py and send message in your WhatsApp

It should work fine

**Comment by cyrisky** [comment]
I already do the step above, but in ngrok it returned a 403 Forbidden when I send message in whatsApp, can you help?

**Comment by Thiru-Malai** [comment]
Make sure you have Paid OPEN-API Key. Free open-api key does not work.

Also append /bot similar to this https://2262-49-204-133-70.ngrok-free.app/bot but replace with your url that is generated from ngrok.

Please let me know if this works and make sure to follow all the steps without missing anything.
